grails-app/domain/bgger/Play.groovy
package bgger

import bgger.security.User

/**
 * Created by mikeh on 11/29/15.
 */
class Play {

    Integer bggId
    User user
    BggGame game
    Integer quantity
    String comments
    Date playedOnDate
    Date dateCreated

    static constraints = {
        comments nullable: true

    }
    static mapping = {
        comments type: 'text'
        sort playedOnDate: "desc"
    }
}

grails-app/controllers/bgger/GameController.groovy
package bgger

import grails.plugin.springsecurity.annotation.Secured

/**
 * Created by req86346 on 11/03/2015.
 */
class GameController {

    @Secured(['ROLE_ADMIN'])
    def index(BggGame game) {

        def geekListItems = GeekListItem.findAllByBggGame(game)

        def playCount = Play.countByGame(game)

        render view: 'index', model: [game: game, geekListItems: geekListItems, playCount: playCount]
    }
}

grails-app/controllers/bgger/PlayController.groovy
package bgger

import grails.plugin.springsecurity.annotation.Secured

/**
 * Created by mikeh on 2/9/16.
 */
@Secured(['ROLE_ADMIN'])
class PlayController {

    def index() {

    }

    def game(BggGame game) {

        def plays = Play.findAllByGame(game, ["max": 50])

        render view: "game", model: [game: game, plays: plays]
    }
}

grails-app/views/game/index.gsp
<html>
<head>
    <meta name="layout" content="main"/>
    <title>${game.name}</title>
</head>

<body>

<div class="row">

    <div class="large-12 columns">

     <h2>${game.name}</h2>

        <h4>Total Plays: <g:link controller="play" action="game" id="${game.id}">${playCount}</g:link></h4>
        <h4><a target="${game.bggId}" href="${game.url}">BGG Link</a></h4>
        <table class="fancy display  no-wrap" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Geeklist</th>
                <th>User</th>
                <th>Number of <br/> Comments</th>
                <th>Post Date</th>
            </tr>
            </thead>

            <tbody>

            <g:each in="${geekListItems}" var="item">
                <tr>
                <td><a target="${game.bggId} " href="${item.url}">${item.geeklist.name}</a>
                    <g:render template="/partials/gameInfo" model="${[bggGame:item.bggGame]}"/>
                </td>
                <td>${item.username}</td>
                    <td>${item.comments.size()}</td>
                    <td>${item.postDate}</td>

                </tr>
            </g:each>

            </tbody>

        </table>
    </div>

</div>
<g:render template="/partials/tableinit"/>
</body>
</html>