grails-app/controllers/bgger/UserItemController.groovy
package bgger

import grails.plugin.springsecurity.annotation.Secured

/**
 * Created by req86346 on 09/17/2015.
 */
class UserItemController {

    def springSecurityService

    def playService

    @Secured(['ROLE_ADMIN'])
    def index() {


        def currentUser = springSecurityService.currentUser

        if (!currentUser) {
            redirect url: '/login'
            return
        }

        def username = currentUser.username

        def myItems = GeekListItem.findAllByUsername(username,[sort: "editDate", order: "desc", max: 100])

        def myComments = GeekListItemComment.findByUsername(username,[sort: "editDate", order: "desc", max: 100])

        myItems.addAll(
                myComments.collect { it.geekListItem}
        )

        def hindex = playService.findHindex(currentUser)

        //def yearlyStats = playService.yearlyStats(currentUser)

        //log.info("Stats: ${yearlyStats}")
        myItems.sort{ a,b -> a.commentDate<=>b.commentDate}

        render view: "index", model: [items: myItems, hindex: hindex]

    }


}

grails-app/views/partials/_gameInfo.gsp
<div class="game-link">
    <g:link controller="game" action="index" id="${bggGame.id}">
        [Game Info]
    </g:link>
</div>

grails-app/views/partials/_geeklist_table.gsp
<table class="fancy display  no-wrap" cellspacing="0" width="100%">
    <thead>
    <tr>
        <td>Game</td>
        <td>List</td>
        <td>User</td>
        <td>Updated</td>
    </tr>
    </thead>
    <tbody>
    <g:each var="item" in="${items}">
        <tr>
            <td><a href="${item.url}" target="${item.bggId}">${item.bggGame.name}</a>

                <g:render template="/partials/gameInfo" model="${[bggGame:item.bggGame]}"/>
            </td>
            <td>
                <g:link controller="geekList" action="index" id="${item.geeklist.id}">
               ${item.geeklist.name}
                </g:link>


            </td>
            <td>${item.username}</td>
            <td>
                <g:if test="${item.username==currentUsername}">
                    <g:link controller="userItem">
                        ${item.editDate}
                    </g:link>

                </g:if>
                <g:else>
                    ${item.editDate}
                </g:else>


            </td>
        </tr>
    </g:each>
    </tbody>
</table>

grails-app/views/partials/_menu.gsp
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class="name">
            <h1><a href="/">BGGer</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon">
        <a href="#">
            <span>Menu</span></a>a></li>
    </ul>

    <section class="top-bar-section">

        <!-- Left Nav Section -->
        <ul class="left">
        <li class="has-form">
            <g:form controller="search" action="search" method="post">
                <div class="row collapse">
                    <div class="large-8 small-9 columns">
                        <input type="text" placeholder="Find Stuff" name="searchTerm">
                    </div>

                    <div class="large-4 small-3 columns">
                        <input type="submit" class="alert button expand" value="Search"/>
                    </div>
                </div>
            </g:form>
        </li>
            <li><g:link controller="userItem" absolute="index">My Item Info</g:link></li>

        </ul>

        <!-- Right Nav Section -->
        <ul class="right">
        </ul>

    </section>
</nav>

grails-app/views/partials/_tableinit.gsp
<g:javascript>
    $(document).ready(function () {
        $('.fancy').DataTable({
            "order": [[3, "desc"]],
            responsive: true
        });
    });

</g:javascript>